services:

  mysql:
    image: mysql:8.0
    container_name: fleetforge-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password --lower_case_table_names=1

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: fleetforge-secret-key-ljnfioewn[309j0jf940djo3powk3oklwkdlkl3md


  vehicle-service:
    build: ./vehicle-service
    container_name: vehicle-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vehicle_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker

  driver-service:
    build: ./driver-service
    container_name: driver-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/driver_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker

  route-service:
    build: ./route-service
    container_name: route-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/route_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker

  trip-service:
    build: ./trip-service
    container_name: trip-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trip_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: fleetforge-secret-key-ljnfioewn[309j0jf940djo3powk3oklwkdlkl3md

  location-service:
    build: ./location-service
    container_name: location-service
    ports:
      - "8086:8086"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/location_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - vehicle-service
      - driver-service
      - route-service
      - trip-service
      - location-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: fleetforge-secret-key-ljnfioewn[309j0jf940djo3powk3oklwkdlkl3md


volumes:
  mysql_data:
